### ISSUE TITLE
Possible issue with either setup.py or pathing command within OLGA

### ISSUE THREAD

**Issue by wyattmcdonnell** [statbiophys/OLGA#13]
Hello! I'm updating our `olga` installation as I saw that BCR light chain models have been added. I'm managing an Anaconda environment for `olga` and ran `python setup.py install` without issue. However, I run into this error when I try to execute `compute_pgen` for the IGK model:

```
(olga) wyatt.mcdonnell@bespin1 [~] [09:55] > olga-compute_pgen --humanIGK
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Check pathing... cannot find the model folder: /mnt/home/wyatt.mcdonnell/anaconda3/envs/olga/lib/python2.7/site-packages/olga-1.2.1-py2.7.egg/olga/default_models/human_B_kappa)
Exiting...
```

Not sure why this is happening, as everything looks to be present and in the right location:
```
(olga) wyatt.mcdonnell@bespin1 [~] [09:57] > ls /mnt/home/wyatt.mcdonnell/anaconda3/envs/olga/lib/python2.7/site-packages/olga-1.2.1-py2.7.egg/olga/default_models/human_B_kappa
.  ..  J_gene_CDR3_anchors.csv  model_marginals.txt  model_params.txt  V_gene_CDR3_anchors.csv
(olga) wyatt.mcdonnell@bespin1 [~] [09:57] > ls /mnt/home/wyatt.mcdonnell/anaconda3/envs/olga/lib/python2.7/site-packages/olga-1.2.1-py2.7.egg/olga/default_models/human_B_lambda
.  ..  J_gene_CDR3_anchors.csv  model_marginals.txt  model_params.txt  V_gene_CDR3_anchors.csv
```

Any ideas as to why this might be happening? Thanks!

**Comment by giulioisac** [comment]
Hello, 
Thanks for reporting this, the problem should be solved now. 
Try `pip install olga --upgrade` or `python setup.py install` again. 
Bests,
Giulio

**Comment by wyattmcdonnell** [comment]
Thanks @giulioisac! I can re-install via `pip`, but I'm not seeing a new commit since `510e7ec` for the repo. Are changes inbound to GitHub for this? If so I'll just wait a little bit to run `setup.py` as you suggested.

**Comment by giulioisac** [comment]
Right, new commit should be now submitted. Let me know if also the setup.py works.

**Comment by wyattmcdonnell** [comment]
Just updated, the new `setup.py` works / the patch did too. Thanks again @giulioisac!
