### ISSUE TITLE
Inconsistent argparse arguments

### ISSUE THREAD

**Issue by zacmon** [statbiophys/OLGA#16]
Hi,

The `generate_sequences.py` script uses [`VDJ_model_folder`](https://github.com/statbiophys/OLGA/blob/845e67144161e857876f921054351aa727e1589f/olga/generate_sequences.py#L169-L170) and the `compute_pgen.py` uses [`set_custom_model_VDJ`](https://github.com/statbiophys/OLGA/blob/845e67144161e857876f921054351aa727e1589f/olga/compute_pgen.py#L299-L300) to specify non-default IGoR-generated models. SONIA appears to use `set_custom_model_VDJ` exclusively. Might it be okay to change `VDJ_model_folder` to `set_custom_model_VDJ` in `generate_sequences.py` for consistency and a better user experience?

Thanks,
Zach

**Comment by giulioisac** [comment]
Hello,

Good idea, I have just added this option. 
If you upgrade with pip you should be able to use the option also with the generate_sequences command.

Best,
Giulio
