### ISSUE TITLE
I got OLGA running in Python 3.7

### ISSUE THREAD

**Issue by dhmay** [statbiophys/OLGA#6]
I forked OLGA, ran 2to3 and touched up some integer-division issues:

https://github.com/dhmay/OLGA

It runs fine, but I haven't done anything to verify that it gives correct output. The integer-division stuff took about 20-30 minutes to fix up, so if you want to make OLGA work in 3.7 that's about the amount of time you could save by folding in my fork. :)

If you wanted to leave the codebase in 2.x but make it so a run of 2to3 would make it run in 3.7 (the reason I didn't just make a pull request), the manual changes I made are all in generation_probability.py. I made a function called "div3int" and called it wherever I made a change. All that would run fine in Python 2.x.

**Comment by penuts7644** [comment]
Would like to see this happening! (especially with python 2's end off support closing in)

**Comment by giulioisac** [comment]
Hello,
OLGA is now compatible with python3.
I close the Issue.
Bests,
Giulio
